name: My First Action

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print Message
        run: echo "Hello Darshan, GitHub Actions is working!"